### ISSUE TITLE
Add keyword to Docker image tag for running load tests

### ISSUE THREAD

**Issue by taddes** [mozilla-services/merino-py#222]
In order to allow contributors to opt-in to load testing on the deployment pipeline, enable signalization via a git commit tag.

The tag should take the form [load test: (abort|warn)]. 

    The abort flag will prevent a stage deployment should the load test fail. 

    The warn flag will output a Slack warning should the load test fail, but still allow for the stage deployment.

Example commit tag:

    feat: Add feature ABC [load test: warn]

    feat: Add feature XYZ [load test: abort]

The commit tag signals load test instructions to Jenkins by modifying the Docker image tag name. The convention looks as follows:

^(?P<environment>stage|prod)(?:-(?P<task>\w+)-(?P<onfailure>warn|abort))?-(?P<commit>[a-z0-9]+)$

Example Docker image tag name:
<img width="464" alt="image-20230228-152205" src="https://user-images.githubusercontent.com/35045299/222857938-5d1ba9b3-6e8a-4dbb-a590-d183717e8397.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2254)

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Not needed, data sync artifact. Real task https://mozilla-hub.atlassian.net/browse/DISCO-2254 ( https://mozilla-hub.atlassian.net/browse/DISCO-2254|smart-link )
