### ISSUE TITLE
Content Moderation Filtering Titles in Indexer

### ISSUE THREAD

**Issue by taddes** [mozilla-services/merino-py#234]
This [task](https://mozilla-hub.atlassian.net/browse/DISCO-2271) is the second part of total content moderation

Rather than having this just in Merino, now we also want to do the title filtering in the Indexing. 

Remember to update any documentation to explain the process for adding manual entries to content moderation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2289)

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Already complete https://mozilla-hub.atlassian.net/browse/DISCO-2271 ( https://mozilla-hub.atlassian.net/browse/DISCO-2271|smart-link )
