### ISSUE TITLE
Add query string normalization to Merino

### ISSUE THREAD

**Issue by taddes** [mozilla-services/merino-py#240]
# Description
The navigational top picks and AdM suggestion lookups are only triggered if the keyword it's written in all lowercase. Upper case or mixed case keywords do not currently result in a lookup.

# Acceptance Criteria:

- Top Picks and AdM return suggestions irrespective of case, regardless of what character may or may not be capitalized in the query string.
- As an added precaution, ensure domain property is lowercased and stripped during indexing (top picks)
- Create a default implementation of` normalize_query()` in the Provider abstract class so providers can implement their own normalization logic, based on their unique needs.
- Add relevant testing

# Issue(s)
[DISCO-2292](https://mozilla-hub.atlassian.net/browse/DISCO-2292) | [Bugzilla-1806970](https://bugzilla.mozilla.org/show_bug.cgi?id=1806970)

[DISCO-2292]: https://mozilla-hub.atlassian.net/browse/DISCO-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2292)

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Data-sync artifact of actual task: https://mozilla-hub.atlassian.net/browse/DISCO-2292 ( https://mozilla-hub.atlassian.net/browse/DISCO-2292|smart-link )
