### ISSUE TITLE
Merino, Contile, Shepherd: Common tasks runbook, how to do a "rollback"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino-py#400]
If there are errors due to a bad change, there should be some instructions on how to rollback the change and trigger a deployment. Let’s have this in a separate runbook, rather than appended to the Deployment information (serves different purposes and having it separate will make it more searchable).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2513)
┆Epic: jira:mozilla-hub.atlassian.net:339012

**Comment by shobhit9957** [comment]
/attempt #400
I would to contribute. can you help me out.

**Comment by mtbottle** [comment]
Hey @shobhit9957 ! Thanks for the interest, but there's actually a PR up for this already that was unlinked! Sorry for the confusion!

**Comment by shobhit9957** [comment]
No worries. Just wanted to contribute.
