### ISSUE TITLE
Why merino -> merino-py

### ISSUE THREAD

**Issue by dharanad** [mozilla-services/merino-py#458]
Hello,

I'm curious to know the primary motivations and rationale behind the decision to rewrite Merino from Rust to Python.
What specific challenges were encountered with the Rust implementation of Merino that led to the decision to rewrite it in Python?

Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2698)

**Comment by ncloudioj** [comment]
Hi @dharanad, thanks for reaching out!

The main reason for the rewrite is that Merino is a cross-functional project at Mozilla that involves various teams in addition to service engineers, and most folks are much more familiar with the Python tech stack than Rust. As an early experimental feature for Firefox, developer productivity and the more mature ecosystem are paramount for us to rapidly prototype new features and iterate. Hence, we decided to rewrite Merino in Python last year and everything worked out quite well thus far.

It's worth noting that as much as we love Python, Rust is still being heavily used by us for many other projects at Mozilla. This rewrite only reflects a specific need for this project, it does not affect the overall adoption of Rust here.

Hope this helps :)

**Comment by dharanad** [comment]
@ncloudioj Thank you for taking the time to explain that so clearly.
